spring:
  application:
    name: gateway-service

server:
  port: 8050
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  prefix: /api
  ignoredServices: '*'
  routes:
    phrasebook:
      path: /phrasebook/**
      serviceId: phrasebook
